name: CD

on:
  push:
    branches:
      - 'rguo*'

  pull_request:
    branches:
      - 'rguo*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: 12.0.x

      - name: Checkout Performance Analyzer package
        uses: actions/checkout@v2

      - name: Build
          run: |
            ./gradlew build buildDeb buildRpm --refresh-dependencies -Dbuild.snapshot=false -x javadoc
            artifact=`ls build/distributions/*.zip`
            rpm_artifact=`ls build/distributions/*.rpm`
            deb_artifact=`ls build/distributions/*.deb`

      - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-west-2

      - name: Upload Artifacts to S3
          run: |
            aws s3 cp $artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/elasticsearch-plugins/performance-analyzer/
            aws s3 cp $rpm_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/rpms/opendistro-performance-analyzer/
            aws s3 cp $deb_artifact s3://artifacts.opendistroforelasticsearch.amazon.com/downloads/debs/opendistro-performance-analyzer/
            aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths "/downloads/*"

